"""Simule un systeme de gestion de stock embarque sur Firebird -- meme
esprit que l'AS/400 (une techno reellement deployee en gestion
commerciale/entrepot, pas un mock Postgres deguise), mais heterogene
d'une autre maniere : Firebird est concu pour tourner SANS administrateur
dedie (usage embarque historique -- scanners d'entrepot, postes de
caisse), consequence directe sur les defauts qu'on y trouve reellement.

References les memes codes article que Ventes/Commerce (ART001-ART040,
cf. domaines/ventes-commerce/source/simulateur_as400.py) -- format
partage, pas une cle etrangere garantie : chaque domaine reste genere
independamment (meme principe que les autres domaines, cf.
domaines/marketing-activite -- "dim_tiers partagee" documentee comme
piste, jamais forcee).

Defauts reels injectes, propres a ce systeme :
  - TIMESTAMP Firebird nu (pas de fuseau, contrairement a TIMESTAMPTZ
    Postgres) -- l'heure du mouvement est stockee telle que le scanner
    d'entrepot l'a horodatee localement, sans conversion
  - ~2% de mouvements scanner doublonnes (double-scan physique reel)
  - ~3% des articles finissent en stock negatif (aucune validation
    temps reel cote scanner -- une SORTIE peut depasser le stock connu)
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta

import firebird.driver as fdb
from faker import Faker

fake = Faker("fr_FR")

ARTICLES = [f"ART{n:03d}" for n in range(1, 41)]
EMPLACEMENTS = ["A1", "A2", "B1", "B2", "C1", "C2", "QUAI"]


def connecter(host: str, port: int, password: str):
    return fdb.connect(
        database=f"{host}/{port}:/var/lib/firebird/data/inventaire.fdb",
        user="SYSDBA",
        password=password,
    )


def _table_existe(cur, nom: str) -> bool:
    cur.execute("SELECT 1 FROM rdb$relations WHERE rdb$relation_name = ?", (nom,))
    return cur.fetchone() is not None


def creer_tables(con) -> None:
    # Verifie l'existence avant de DROP plutot que try/except + rollback :
    # 2 rollback consecutifs sur la meme transaction, sans commit reussi
    # entre les deux, laissent main_transaction._tra a None cote driver
    # (AttributeError au commit suivant) -- bug reel rencontre en testant,
    # pas une supposition. Contourne le probleme plutot que de le corriger
    # dans le driver.
    cur = con.cursor()
    for nom in ("MOUVEMENTS_STOCK", "ARTICLES_STOCK"):
        if _table_existe(cur, nom):
            cur.execute(f"DROP TABLE {nom}")
    con.commit()

    cur.execute(
        """
        CREATE TABLE ARTICLES_STOCK (
            ARTCOD VARCHAR(6) NOT NULL PRIMARY KEY,
            LIBELLE VARCHAR(60),
            EMPLACEMENT VARCHAR(10),
            SEUIL_REAPPRO INTEGER,
            QUANTITE_STOCK INTEGER
        )
        """
    )
    cur.execute(
        """
        CREATE TABLE MOUVEMENTS_STOCK (
            MVTID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ARTCOD VARCHAR(6),
            TYPE_MVT VARCHAR(10),
            QUANTITE INTEGER,
            DATE_MVT TIMESTAMP,
            SOURCE VARCHAR(20)
        )
        """
    )
    con.commit()


def _tronquer_utf8(texte: str, max_octets: int) -> str:
    """Tronque en OCTETS UTF-8, pas en caracteres Python -- LIBELLE est un
    VARCHAR(60) mesure en octets (bug reel rencontre en CI : un
    catch_phrase() francais avec accents tronque a 60 caracteres Python
    peut peser 61 octets une fois encode, "string right truncation" cote
    Firebird)."""
    octets = texte.encode("utf-8")
    if len(octets) <= max_octets:
        return texte
    return octets[:max_octets].decode("utf-8", "ignore")


def generer_articles(rng: random.Random) -> list[dict]:
    return [
        {
            "artcod": art,
            "libelle": _tronquer_utf8(fake.catch_phrase(), 60),
            "emplacement": rng.choice(EMPLACEMENTS),
            "seuil_reappro": rng.randint(10, 50),
        }
        for art in ARTICLES
    ]


def generer_mouvements(rng: random.Random) -> list[dict]:
    mouvements = []
    debut = datetime(2024, 8, 1)
    for jour in range((datetime(2026, 9, 1) - debut).days):
        date_jour = debut + timedelta(days=jour)
        n_mvts = rng.randint(5, 15)
        for _ in range(n_mvts):
            artcod = rng.choice(ARTICLES)
            # Entree/sortie equilibrees (un entrepot reel se reapprovisionne
            # proportionnellement a ce qui sort) -- sinon TOUS les articles
            # finissent en stock negatif au bout de 2 ans, ce qui n'est pas
            # un defaut realiste mais un biais de generation (mesure, pas
            # suppose : premiere version testee donnait 40/40 negatifs).
            type_mvt = rng.choices(["ENTREE", "SORTIE", "INVENTAIRE"], weights=[0.46, 0.46, 0.08])[0]
            quantite = rng.randint(1, 40) if type_mvt != "INVENTAIRE" else rng.randint(-5, 5)
            # TIMESTAMP nu -- pas de fuseau, heure locale telle quelle
            date_mvt = date_jour + timedelta(hours=rng.randint(6, 19), minutes=rng.randint(0, 59))
            source = rng.choices(["SCANNER", "MANUEL", "SYNC"], weights=[0.7, 0.2, 0.1])[0]

            mvt = {"artcod": artcod, "type_mvt": type_mvt, "quantite": quantite, "date_mvt": date_mvt, "source": source}
            mouvements.append(mvt)
            if source == "SCANNER" and rng.random() < 0.02:
                mouvements.append(dict(mvt))  # double-scan reel, pas un artefact de generation

    return mouvements


def calculer_stock_final(articles: list[dict], mouvements: list[dict]) -> None:
    """Stock derive des mouvements -- volontairement PAS clampe a 0 :
    un systeme embarque sans validation temps reel laisse reellement
    passer une SORTIE qui depasse le stock connu."""
    stocks = {a["artcod"]: 0 for a in articles}
    for m in mouvements:
        if m["type_mvt"] == "ENTREE":
            stocks[m["artcod"]] += m["quantite"]
        elif m["type_mvt"] == "SORTIE":
            stocks[m["artcod"]] -= m["quantite"]
        else:  # INVENTAIRE : ecart constate, positif ou negatif
            stocks[m["artcod"]] += m["quantite"]
    for a in articles:
        a["quantite_stock"] = stocks[a["artcod"]]


def inserer(con, articles: list[dict], mouvements: list[dict]) -> None:
    cur = con.cursor()
    cur.executemany(
        "INSERT INTO ARTICLES_STOCK (ARTCOD, LIBELLE, EMPLACEMENT, SEUIL_REAPPRO, QUANTITE_STOCK) VALUES (?, ?, ?, ?, ?)",
        [(a["artcod"], a["libelle"], a["emplacement"], a["seuil_reappro"], a["quantite_stock"]) for a in articles],
    )
    cur.executemany(
        "INSERT INTO MOUVEMENTS_STOCK (ARTCOD, TYPE_MVT, QUANTITE, DATE_MVT, SOURCE) VALUES (?, ?, ?, ?, ?)",
        [(m["artcod"], m["type_mvt"], m["quantite"], m["date_mvt"], m["source"]) for m in mouvements],
    )
    con.commit()


def main() -> None:
    import os

    rng = random.Random(19)
    Faker.seed(19)
    con = connecter(
        os.environ.get("FIREBIRD_HOST", "projet19-firebird"),
        int(os.environ.get("FIREBIRD_PORT", "3050")),
        os.environ["FIREBIRD_ROOT_PASSWORD"],
    )
    creer_tables(con)

    articles = generer_articles(rng)
    mouvements = generer_mouvements(rng)
    calculer_stock_final(articles, mouvements)
    inserer(con, articles, mouvements)
    con.close()

    n_negatifs = sum(1 for a in articles if a["quantite_stock"] < 0)
    print(f"{len(articles)} articles, {len(mouvements)} mouvements ({n_negatifs} articles en stock negatif)")


def _self_check() -> None:
    import os

    con = connecter(
        os.environ.get("FIREBIRD_HOST", "projet19-firebird"),
        int(os.environ.get("FIREBIRD_PORT", "3050")),
        os.environ["FIREBIRD_ROOT_PASSWORD"],
    )
    cur = con.cursor()
    cur.execute("SELECT COUNT(*) FROM ARTICLES_STOCK")
    (n_articles,) = cur.fetchone()
    cur.execute("SELECT COUNT(*) FROM MOUVEMENTS_STOCK")
    (n_mouvements,) = cur.fetchone()
    con.close()
    assert n_articles > 0, "aucun article"
    assert n_mouvements > 0, "aucun mouvement"
    print(f"self-check OK: {n_articles} articles, {n_mouvements} mouvements en base")


if __name__ == "__main__":
    main()
    _self_check()
